### ISSUE TITLE
Sql Error

### ISSUE THREAD

**Issue by sdiwo** [StrikeOrg/strike-search#3]
it seams there is an Error in sql
am getting this error with torrent table

> You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'TRANSACTIONAL=0 AUTO_INCREMENT=7019530' at line 22

> CREATE TABLE IF NOT EXISTS `torrents` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `torrent_hash` varchar(40) NOT NULL,
  `torrent_title` tinytext NOT NULL,
  `torrent_category` varchar(50) NOT NULL,
  `sub_category` varchar(50) NOT NULL,
  `torrent_page` varchar(255) NOT NULL,
  `seeds` int(11) NOT NULL,
  `leeches` int(11) NOT NULL,
  `file_count` int(11) NOT NULL,
  `size` int(11) NOT NULL,
  `upload_date` varchar(35) NOT NULL,
  `uploader_username` varchar(50) NOT NULL,
  `verified` tinyint(4) NOT NULL,
  `imdbid` varchar(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `torrent_hash` (`torrent_hash`),
  KEY `seeds` (`seeds`),
  KEY `sub_category` (`sub_category`),
  KEY `torrent_category` (`torrent_category`),
  FULLTEXT KEY `torrent_title` (`torrent_title`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC TRANSACTIONAL=0 AUTO_INCREMENT=7019530 ;

http://sqlfiddle.com/

**Comment by Codeusa** [comment]
You can remove the last part 

ROW_FORMAT=DYNAMIC TRANSACTIONAL=0 AUTO_INCREMENT=7019530

**Comment by sdiwo** [comment]
thank you
thank solved it.
